#!/bin/bash

# ... fetching from Ensembl Genomes

YEAST_ANNOTATION_GTF="ftp://ftp.ensembl.org/pub/release-98/gtf/saccharomyces_cerevisiae/Saccharomyces_cerevisiae.R64-1-1.98.gtf.gz"
YEAST_ASSEMBLY="ftp://ftp.ensembl.org/pub/release-98/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna_sm.toplevel.fa.gz"

wget -O $(basename $YEAST_ANNOTATION_GTF) $YEAST_ANNOTATION_GTF
wget -O $(basename $YEAST_ASSEMBLY)   $YEAST_ASSEMBLY
gunzip Saccharomyces_cerevisiae.*gz

#rRNA coding regions were collected from 
#
#	https://www.yeastgenome.org/search?category=locus&feature_type=rRNA_gene&page=0&q=rRNA_gene
#
#and saved as rna_coding.fasta. The file is used for removing rRNA contaminants
#from the reads using tagdust.

ln -rs rna_coding.fasta Sc_grRNA.fa
